<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SAVT extends Model
{
    use HasFactory;
    public $table = 'tbl_savt';

    protected $fillable = [
        'supplier_pmu_ppu',
        'supplier_feeder_no',
        'sec_from',
        'sec_to',
        'tiang_no',
        'road_name',
        'voltan_kv',
        'abc_size_mmp',
        'abc_panjang_meter',
        'image_abc_size',
        'image_abc_panjang',
        'bare_size_mmp',
        'bare_panjang_meter',
        'underground_cabel_size_mmp',
        'underground_cabel_length_meter',
        'eqp_no_auto_circuit_recloser',
        'eqp_no_load_break_switch',
        'eqp_no_isolator_switch',
        'eqp_no_set_lfi',
        'duty_year',
        'tiang_rust',
        'tiang_leaning',
        'tiang_tarikh_repair_done',
        'conductor_sagging',
        'conductor_torn',
        'conductor_broken',
        'conductor_hotspot',
        'conductor_tarikh_repair_done',
        'umbang_sagging',
        'umbang_disconnect',
        'umbang_tarikh_repair_done',
        'cabel_terminate_crossing',
        'cabel_terminate_hotspot',
        'cabel_terminate_tarikh_repair_done',
        'lightning_arrester_ocp_broken',
        'lightning_arrester_ocp_disconnected',
        'lightning_arrester_ocp_hot_spot',
        'lightning_arrester_ocp_tarikh_repair_done',
        'lightning_arrester_pac_broken',
        'lightning_arrester_pac_disconnected',
        'lightning_arrester_pac_hot_spot',
        'lightning_arrester_pac_tarikh_repair_done',
        'need_rentis',
        'rentis_tarikh_repair_done',
        'switch_link_need_repair',
        'switch_link_need_tarikh_repair_done',
        'tiang_needs_repaint',
        'tiang_needs_repaint_tarikh_repair_done',
        'umbang_insulation_status',
        'earth_bounding_status',
        'earth_bounding_hotspt',
        'earthbounding_ultrasound_status',
        'earth_bounding_repair_done',
        'cabel_tray_change',
        'cabel_tray_repair_done_date',
        'suspension_clamp_change',
        'sc_repair_done_date',
        'triangular_braker_change',
        'triangular_braker_repair_done_date',
        'crossarm_rust',
        'crossarm_bent',
        'crossarm_repair_done_date',
        'earth_crossarm_rust',
        'earth_crossarm_bent',
        'earth_crossarm_repair_done_date',
        'ce_sagging',
        'ce_btc',
        'ce_broken',
        'ce_repair_done_date',
        'wte_hanging_disconnected',
        'wte_repair_done_date',
        'insulation_flashover',
        'insulation_full',
        'insulation_broken',
        'insulation_hotspot',
        'insulation_defect_repair_date',
        'lcol_ripped_off',
        'lcol_hotspot',
        'lcol_repair_date',
        'jumper_need_repair',
        'jumper_hotspot',
        'jumper_repair_date',
        'pg_cc_need_change',
        'pg_cc_hotspot',
        'pg_cc_repair_date',
        'climbing_barrier_need_change',
        'cb_repair_date',
        'arcing_horn_need_repair',
        'ah_repair_done_date',
        'lfi_break_date',
        'lfi_repair_date',
        'remarks', 
        'savt_image_1',
        'savt_image_2',
        'savt_image_3',
        'savt_image_4',
        'savt_image_5',
    ];

}
